# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(596, 301)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 591, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.doubleSpinBoxFreq = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.doubleSpinBoxFreq.setFont(font)
        self.doubleSpinBoxFreq.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxFreq.setProperty("showGroupSeparator", True)
        self.doubleSpinBoxFreq.setDecimals(3)
        self.doubleSpinBoxFreq.setMinimum(1.0)
        self.doubleSpinBoxFreq.setMaximum(4000000000.0)
        self.doubleSpinBoxFreq.setProperty("value", 121000.0)
        self.doubleSpinBoxFreq.setObjectName("doubleSpinBoxFreq")
        self.horizontalLayout.addWidget(self.doubleSpinBoxFreq)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.checkBoxRoundToStep = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBoxRoundToStep.setObjectName("checkBoxRoundToStep")
        self.horizontalLayout.addWidget(self.checkBoxRoundToStep)
        self.comboBoxStepList = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBoxStepList.setObjectName("comboBoxStepList")
        self.horizontalLayout.addWidget(self.comboBoxStepList)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(170, 90, 382, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton3M5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton3M5.setObjectName("pushButton3M5")
        self.gridLayout.addWidget(self.pushButton3M5, 1, 0, 1, 1)
        self.pushButtonG2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonG2.setObjectName("pushButtonG2")
        self.gridLayout.addWidget(self.pushButtonG2, 5, 3, 1, 1)
        self.pushButton472 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton472.setObjectName("pushButton472")
        self.gridLayout.addWidget(self.pushButton472, 0, 1, 1, 1)
        self.pushButton18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton18.setObjectName("pushButton18")
        self.gridLayout.addWidget(self.pushButton18, 2, 3, 1, 1)
        self.pushButton7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton7.setObjectName("pushButton7")
        self.gridLayout.addWidget(self.pushButton7, 1, 3, 1, 1)
        self.pushButton1M8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton1M8.setObjectName("pushButton1M8")
        self.gridLayout.addWidget(self.pushButton1M8, 0, 3, 1, 1)
        self.pushButton50 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton50.setObjectName("pushButton50")
        self.gridLayout.addWidget(self.pushButton50, 5, 0, 1, 1)
        self.pushButton138 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton138.setObjectName("pushButton138")
        self.gridLayout.addWidget(self.pushButton138, 0, 0, 1, 1)
        self.pushButtonG1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonG1.setObjectName("pushButtonG1")
        self.gridLayout.addWidget(self.pushButtonG1, 5, 1, 1, 1)
        self.pushButton5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton5.setObjectName("pushButton5")
        self.gridLayout.addWidget(self.pushButton5, 1, 1, 1, 1)
        self.pushButton14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton14.setObjectName("pushButton14")
        self.gridLayout.addWidget(self.pushButton14, 2, 1, 1, 1)
        self.pushButton10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton10.setObjectName("pushButton10")
        self.gridLayout.addWidget(self.pushButton10, 2, 0, 1, 1)
        self.pushButton28 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton28.setObjectName("pushButton28")
        self.gridLayout.addWidget(self.pushButton28, 3, 3, 1, 1)
        self.pushButton24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton24.setObjectName("pushButton24")
        self.gridLayout.addWidget(self.pushButton24, 3, 1, 1, 1)
        self.pushButton21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton21.setObjectName("pushButton21")
        self.gridLayout.addWidget(self.pushButton21, 3, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 90, 142, 110))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonVfoAB = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Adlam")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonVfoAB.setFont(font)
        self.pushButtonVfoAB.setObjectName("pushButtonVfoAB")
        self.verticalLayout.addWidget(self.pushButtonVfoAB)
        self.pushButtonSplit = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonSplit.setObjectName("pushButtonSplit")
        self.verticalLayout.addWidget(self.pushButtonSplit)
        self.pushButtonSync = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButtonSync.setObjectName("pushButtonSync")
        self.verticalLayout.addWidget(self.pushButtonSync)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 50, 152, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBoxSyncHamlib = QtWidgets.QCheckBox(self.verticalLayoutWidget_2)
        self.checkBoxSyncHamlib.setObjectName("checkBoxSyncHamlib")
        self.verticalLayout_2.addWidget(self.checkBoxSyncHamlib)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 596, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "  Freq :"))
        self.label_2.setText(_translate("MainWindow", "   kHz"))
        self.checkBoxRoundToStep.setText(_translate("MainWindow", " round\n"
" to step"))
        self.pushButton3M5.setText(_translate("MainWindow", "3.5"))
        self.pushButtonG2.setText(_translate("MainWindow", "GENE2"))
        self.pushButton472.setText(_translate("MainWindow", "472k"))
        self.pushButton18.setText(_translate("MainWindow", "18"))
        self.pushButton7.setText(_translate("MainWindow", "7"))
        self.pushButton1M8.setText(_translate("MainWindow", "1.8"))
        self.pushButton50.setText(_translate("MainWindow", "50"))
        self.pushButton138.setText(_translate("MainWindow", "138k"))
        self.pushButtonG1.setText(_translate("MainWindow", "GENE1"))
        self.pushButton5.setText(_translate("MainWindow", "5"))
        self.pushButton14.setText(_translate("MainWindow", "14"))
        self.pushButton10.setText(_translate("MainWindow", "10"))
        self.pushButton28.setText(_translate("MainWindow", "28"))
        self.pushButton24.setText(_translate("MainWindow", "24"))
        self.pushButton21.setText(_translate("MainWindow", "21"))
        self.pushButtonVfoAB.setText(_translate("MainWindow", "A/B"))
        self.pushButtonSplit.setText(_translate("MainWindow", "SPLIT"))
        self.pushButtonSync.setText(_translate("MainWindow", "Sync"))
        self.checkBoxSyncHamlib.setText(_translate("MainWindow", "Sync with Hamlib"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
